### PR TITLE
What about using constrained eager loading?

### PR DESCRIPTION
**Pull request by JesseLeite**
Hey man! 🌷

Regarding your eager loading problem (#1), what about using constrained eager loading?

In my PR here, I added a `latest()` scope to your `Asset` model.  This will allow you to use constrain your eager loading to that scope.

Then in your `latestAsset()` method in your `Product` model, I removed the brackets to prevent new queries.

screen shot 2018-03-23 at 8 52 34 pm

Whoops, that subtle _hire me_ tweet creepin' in there 😬

Anyway, I see what you mean about wanting a `hasOne` style relationship, which would definitely be nice semantically.  However, this scope + constrained eager loading technique is how I've dealt with it in past.  Curious on your thoughts?

### CODE REVIEW

**Comment by JesseLeite** [comment]
Whoops that subtle hire me tweet creepin' in there, sorry about that 😱

**Comment by JesseLeite** [comment]
Whoops, that subtle hire me tweet creepin' in there 😬

Anyway, I see what you mean about wanting a `hasOne` style relationship, which would be nice semantically.  However, this scope + constrained eager loading technique is how I've dealt with it in past.  Curious on your thoughts!

**Comment by jasonvarga** [comment]
Hey thanks for spending time on this, I appreciate it.

This is ultimately the solution I went with - to just use the collection by removing the brackets instead of using the query, and eager load.

I'm not sure what the `scopeLatest` was doing here. Everything still seemed to work fine without it.

Also, your subtle screenshot background did not go unnoticed. I had a laugh.

**Comment by JesseLeite** [comment]
>I'm not sure what the scopeLatest was doing here. Everything still seemed to work fine without it.

Everything would work fine either way.  The purpose of the scope was to constrain the eager loading to only the latest asset for each product (rather than loading all assets onto each product).

```php
$products = Product::with(['assets' => function ($query) {
    $query->latest();
}])->get();
```

Honestly, it's optional though.  If query performance isn't a problem, keep it simple and eager load all the assets as you were already doing! 👌

```php
$products = Product::with('assets')->get();
```

>Also, your subtle screenshot background did not go unnoticed. I had a laugh.

😂 I'm definitely interested though, would love to chat!

**Comment by JesseLeite** [comment]
Closing in favor of #3

**Pull request closed without merging**
